### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by CJYKK** [Buddelbubi/PluginManager#1]
How do you build this plugin? Please tell me. Thank you!

**Comment by CJYKK** [comment]
I'm really new to Nukkit plugin programming...

**Comment by Buddelbubi** [comment]
Why do you have to build it? It is on Cloudburst free to download.
https://cloudburstmc.org/resources/pluginmanager.776/

**Comment by CJYKK** [comment]
Because i want to make a translation for it. lol
Sorry for my bad English, writing commits in English is not my strong suit.

**Comment by CJYKK** [comment]
*By editing the source code directly.

**Comment by Buddelbubi** [comment]
Then just get the code in your coding program. I just uploaded the eclipse project folder

**Comment by CJYKK** [comment]
Oh, thank you very much!
